kind: Secret
apiVersion: v1
metadata:
  name: {{ include "web-application.fullname" . }}-secret
  labels:
    helm.sh/chart: {{ include "web-application.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    workshop: phpuk19
data:
  passcode.txt: {{ .Values.passcode | b64enc }}
